# Generated by Django 4.1.1 on 2022-09-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='auctionlisting',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='description',
            field=models.TextField(default='', max_length=220),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='image',
            field=models.ImageField(blank=True, default='', height_field=50, upload_to='', width_field=50),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
