# Generated by Django 4.1.1 on 2022-09-19 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_delete_auctionlisting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
